### ISSUE TITLE
Result checking

### ISSUE THREAD

**Issue by OlehOnyshchak** [Netmisha/trs#13]
When we write in "result" line everything which is not pure decimal number (e.g. "hello", "as123", "_1" ) it is treated like a 0 and therefore can return "passed" result. Also it treat each string which starts with decimal numbers just like this subsequence with decimal nubmbers (e.g. "123^2" = "123" , "123e2113" = "123" ). As for me it must be handled by verify function

**Comment by mishasup** [comment]
fixed
